using System.Text;

namespace LocalisationStudio.Core;

public static class CodeExporter
{
    // IDs stay dictionary keys: punctuation, Unicode and C# / C++ keywords are safe.
    public static string CSharp(TranslationDocument document)
    {
        document.Validate();
        var code = new StringBuilder("""
// Generated by Localisation Studio. Edit the accompanying .localization.json file.
using System;
using System.Collections.Generic;

namespace GeneratedLocalization
{
    public sealed class Localization
    {
        public static Localization Instance { get; } = new Localization();
        private Localization() { }
        private readonly Dictionary<string, Dictionary<string, string>> data =
            new Dictionary<string, Dictionary<string, string>>(StringComparer.Ordinal)
            {

""");
        foreach (var entry in document.Entries)
        {
            code.Append("                { ").Append(CsLiteral(entry.Id))
                .AppendLine(", new Dictionary<string, string>(StringComparer.Ordinal) {");
            foreach (var language in document.Languages)
                code.Append("                    { ").Append(CsLiteral(language)).Append(", ")
                    .Append(CsLiteral(document.Value(entry, language))).AppendLine(" },");
            code.AppendLine("                } },");
        }
        code.AppendLine("            };");
        code.Append("        public string DefaultLanguage => ").Append(CsLiteral(document.Languages[0])).AppendLine(";");
        code.Append("        public IReadOnlyList<string> Languages { get; } = Array.AsReadOnly(new string[] { ")
            .AppendJoin(", ", document.Languages.Select(CsLiteral)).AppendLine(" });");
        code.Append("""

        public string Get(string id, string language)
        {
            if (id == null) throw new ArgumentNullException(nameof(id));
            if (language == null) throw new ArgumentNullException(nameof(language));
            if (!data.TryGetValue(id, out var values)) return id;
            if (values.TryGetValue(language, out var value)) return value;
            return values.TryGetValue(DefaultLanguage, out value) ? value : id;
        }
    }
}
""");
        return code.ToString();
    }

    public static (string Header, string Source) Cpp(TranslationDocument document, string headerFileName)
    {
        document.Validate();
        if (string.IsNullOrEmpty(headerFileName) || headerFileName.Any(c =>
            !(char.IsAsciiLetterOrDigit(c) || c is '.' or '_' or '-')))
            throw new InvalidDataException("Nom du fichier C++ : utilisez lettres ASCII, chiffres, points, tirets ou underscores.");
        const string header = """
// Generated by Localisation Studio. C++17. Strings are UTF-8.
#pragma once
#include <string>
#include <unordered_map>
#include <vector>

namespace generated_localization {
class Localization final {
public:
    static const Localization& Instance();
    std::string Get(const std::string& id, const std::string& language) const;
    const std::vector<std::string>& Languages() const noexcept { return languages_; }
    const std::string& DefaultLanguage() const noexcept { return languages_.front(); }
    Localization(const Localization&) = delete;
    Localization& operator=(const Localization&) = delete;
private:
    Localization();
    std::vector<std::string> languages_;
    std::unordered_map<std::string, std::unordered_map<std::string, std::string>> data_;
};
}
""";
        var source = new StringBuilder("// Generated by Localisation Studio. UTF-8 values encoded as bytes.\n#include \"")
            .Append(headerFileName).AppendLine("\"\n\nnamespace generated_localization {");
        source.AppendLine("const Localization& Localization::Instance() {\n    static const Localization instance;\n    return instance;\n}");
        source.Append("Localization::Localization()\n    : languages_{")
            .AppendJoin(", ", document.Languages.Select(CppLiteral)).AppendLine("}, data_{");
        foreach (var entry in document.Entries)
        {
            source.Append("        {").Append(CppLiteral(entry.Id)).AppendLine(", {");
            foreach (var language in document.Languages)
                source.Append("            {").Append(CppLiteral(language)).Append(", ")
                    .Append(CppLiteral(document.Value(entry, language))).AppendLine("},");
            source.AppendLine("        }},");
        }
        source.Append("""
    } {}

std::string Localization::Get(const std::string& id, const std::string& language) const {
    const auto entry = data_.find(id);
    if (entry == data_.end()) return id;
    const auto value = entry->second.find(language);
    if (value != entry->second.end()) return value->second;
    const auto fallback = entry->second.find(DefaultLanguage());
    return fallback != entry->second.end() ? fallback->second : id;
}
}
""");
        return (header, source.ToString());
    }

    private static string CsLiteral(string value)
    {
        var text = new StringBuilder("\"");
        foreach (char c in value)
        {
            if (c == '\\') text.Append("\\\\");
            else if (c == '"') text.Append("\\\"");
            else if (c < 32 || c > 126) text.Append("\\u").Append(((int)c).ToString("X4"));
            else text.Append(c);
        }
        return text.Append('"').ToString();
    }

    private static string CppLiteral(string value)
    {
        var text = new StringBuilder("\"");
        foreach (byte b in Encoding.UTF8.GetBytes(value))
        {
            if (b == '\\') text.Append("\\\\");
            else if (b == '"') text.Append("\\\"");
            else if (b < 32 || b > 126) text.Append('\\').Append(Convert.ToString(b, 8).PadLeft(3, '0'));
            else text.Append((char)b);
        }
        return text.Append('"').ToString();
    }
}
